### PR TITLE
Internationalization for menu items

### PR DESCRIPTION
**Pull request by hemisemidemipresent**
Note that some things need to be moved to firebase for it to work in production

### CODE REVIEW

**Comment by Jasonnor** [comment]
Cool! Thanks a lot, I will update Firebase and test ASAP 😍

**Comment by Jasonnor** [comment]
TODO for me:
1. Update `https://srv.thpatch.net/lang_${lang}/stringdefs.js` content to Firebase
2. Put title code to `th-song.json`
3. Update i18n code to get title data from Firebase
4. Make a cache for switching back to Japanese

**Comment by hemisemidemipresent** [comment]
Will the updating of the content on firebase be done manually or can it be done automatically?

**Comment by Jasonnor** [comment]
It's all manual updates now!

**Comment by hemisemidemipresent** [comment]
Yeah perhaps it would be better to get translations from the source itself rather than having to update firebase manually

**Comment by Jasonnor** [comment]
Done! Let me test in GitHub pages

**Comment by Jasonnor** [comment]
It seems to work well!

**Review by Jasonnor — APPROVED** [review]
LGTM

**Pull request merged**
