### PR TITLE
Fix #28 for th07.5, 10.5, 12.3, 12.8, 13.5, 14.5, 15.5

### LINKED ISSUE #26: Avoid background image fade in also fade other component
when the image fades into another image, everything else fades with the image

especially obvious when the menu is open and image changes

### LINKED ISSUE #28: Music song numbers off
see [this comment](https://github.com/Jasonnor/th-music-video-generator/issues/13#issuecomment-1008024104) on how this will make #13 easier to implement

edit: list:

-    [x] th01
-    [x] th02
-    [x] th03
-    [x] th04
-    [x] th05
-    [x] th06
-    [x] th07
-    [ ] th07.5
-    [x] th08
-    [x] th09
-    [x] th09.5
-    [x] th10
-    [ ] th10.5
-    [x] th11
-    [x] th12
-    [ ] th12.3
-    [x] th12.5
-    [ ] th12.8
-    [x] th13
-    [ ] th13.5
-    [x] th14
-    [x] th14.3
-    [ ] th14.5
-    [x] th15
-    [ ] th15.5
-    [x] th16

### PR DESCRIPTION
**Pull request by hemisemidemipresent**
again this is not tested yet, there might be some mistakes when renaming

I made a tracker on issue #28

### CODE REVIEW

**Comment by hemisemidemipresent** [comment]
just checking in how's this going

**Comment by Jasonnor** [comment]
> just checking in how's this going

I am in the process of determining the consistency of song name and file name, and may merge in the next two days. 

Thanks again for the contribution! 😄

**Review by Jasonnor — APPROVED** [review]
LGTM

**Comment by hemisemidemipresent** [comment]
> > just checking in how's this going
> 
> I am in the process of determining the consistency of song name and file name, and may merge in the next two days.
> 
> Thanks again for the contribution! 😄

no problem!

**Pull request merged**
